<?php 
$error = 'error-unauthorized-controller';
?>
<div class="row">
<div class="col-md-6 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><h1>Oops!</h1>
				<h2>403 Forbidden</h2></h3>
            </div>
            <div class="panel-body">
                <div class="error-details">
					    <?php if ($error == 'error-unauthorized-controller') : ?>
					        You are not authorized to access this resources					        .
					    <?php elseif ($error == 'error-unauthorized-route') : ?>
					        You are not authorized to access <?php echo $route;?>.
					    <?php elseif ($error == 'error-unauthorized') : ?>
					        You are not authorized <?php echo $reason; ?>.
					    <?php else : ?>
					    An unknown error occured.
					    <?php endif;?>

				</div> <!-- /error-details -->

				<div class="error-actions">
					<a href="<?php echo $this->url('home');?>" class="btn btn-large btn-primary">
						<span class="glyphicon glyphicon-chevron-left"></span>
						&nbsp;
						Back to Dashboard
					</a>

				</div> <!-- /error-actions -->
            </div>
        </div>
    </div>
</div>


<?php 

var_dump()


?>
